#!/bin/sh
s6-svwait /s6/ss
kcptun-server -l :${KCPTUN_PORT:-444} \
              -t 127.0.0.1:${SERVER_PORT:-443} \
              --crypt ${KCPTUN_CRYPT:-none} \
              --mtu ${KCPTUN_MTU:-1200} \
              --nocomp \
              --mode ${KCPTUN_MODE:-normal} \
              --dscp ${KCPTUN_DSCP:-46}
