#!/bin/sh
ss-server -s ${SERVER_ADDR:-0.0.0.0} \
          -p ${SERVER_PORT:-443} \
          -k ${PASSWORD:-$(hostname)} \
          -m ${METHOD:-chacha20} \
          -t ${TIMEOUT:-300} \
          -d ${DNS_ADDR:-8.8.8.8} \
          --fast-open -u -A
