name: build

on:
  push:
    branches:
      - "master"

jobs:
  bake:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Get build date
        run: echo "DATE=$(date -u '+%Y%m%d%H%M')" >> $GITHUB_ENV
      - name: Build and push
        uses: docker/bake-action@master
        with:
          push: true
          no-cache: true
      - name: Update repo description
        run: ./sync-description.py
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
